import Head from 'next/head'
import { Inter } from '@next/font/google'
import { useState } from 'react'
import Display from '@/components/Display/Index'
import { DataType, User } from '@/types'
import { Toaster } from 'react-hot-toast'
import SeletedTree from '@/components/SeletedTree'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [response, setResponse] = useState<User | null>(null)
  const [selectedOptionsTree, setSelectedOptionsTree] = useState<DataType[] | null>(null)
  
  return (
    <>
      <Head>
        <title>Coding Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-slate-800 text-white min-h-screen w-full flex flex-col lg:flex-row gap-6 justify-center items-center'>
        
        
       <div className='mx-5 lg:mx-0'>
          <h1 className='text-center text-2xl'>Sector Selector</h1>
          <Display setResponse={setResponse} setSelectedOptionsTree={setSelectedOptionsTree} />
       </div>

        {
          response && (
            <div className='mx-5 lg:mx-0'>
                <h1 className='text-center'>Edit data for <span className='font-bold'>{response.name}</span></h1>
                <h1 className='text-xl font-bold'>Selected Sectors</h1>
                <SeletedTree selectedArr={selectedOptionsTree} />
                <Display data={response} setResponse={setResponse} setSelectedOptionsTree={setSelectedOptionsTree} />
            </div>
          )
        }
    </div>
    <Toaster />
    </>
  )
}
